version: '3.2'
services:
  postgres:
    image: lovearuis/postgres-plv8:11.2
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - /Users/jason/git/youtube-collector-postgre-model/postgresql_db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:latest
    # image: hasura/graphql-engine:v1.0.0-beta.2
    # https://github.com/hasura/graphql-engine/pull/1968/files
    # https://docs.hasura.io/1.0/graphql/manual/migrations/auto-apply-migrations.html#applying-only-metadata
    # image: hasura/graphql-engine:v1.0.0-beta.2.cli-migrations
    ports:
      - '8082:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://example:example@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
      ## jwt secret must same as server side
      HASURA_GRAPHQL_JWT_SECRET: '{
        "type": "HS256",
        "key": "123jwtsecret321123jwtsecret321123jwtsecret321123jwtsecret321"
        }'
      #https://github.com/hasura/graphql-engine/pull/1968/files
      #https://docs.hasura.io/1.0/graphql/manual/migrations/auto-apply-migrations.html#applying-only-metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      # HASURA_GRAPHQL_CORS_DOMAIN: https://*.sharemytube.com,https://sharemytube.com,http://*.sharemytube.com
    volumes:
      #https://github.com/hasura/graphql-engine/pull/1968/files
      #https://docs.hasura.io/1.0/graphql/manual/migrations/auto-apply-migrations.html#applying-only-metadata
      - ./graphql-engine/metadata.json:/migrations/metadata.json
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
volumes:
  db_data:
